### ISSUE TITLE
312, 322 lines in helpers.py.

### ISSUE THREAD

**Issue by lottopotato** [glederrey/camogen#2]
Thank you. It is a cool code.
I find 314, 324 lines in helpers.py is strange.

`for y in range(int(pixel_h / 2), pattern.width, pixel_h):`

`sample_y = min(pattern.width-1, max(0, sample_y))`

I think maybe it's height. than width.

Again thank to.

**Comment by glederrey** [comment]
Hi, 

Thanks a lot. That was definitely an issue. I never tried to build a rectangle image. =) 

The issue has been fixed now. Thanks again!
